version: 2.1

jobs:
  # Build job
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build Project
          command: echo "Building the project..."
          # Add any build commands here, e.g., compiling assets, etc.

  # Test job
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run Tests
          command: echo "Running tests..."
          # Add any test commands here, e.g., running unit tests, linting, etc.

  # Deploy job
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Nginx
          command: sudo apt-get update && sudo apt-get install -y nginx
      - run:
          name: Deploy index.html
          command: |
            sudo mv index.html /var/www/html/index.html
            sudo service nginx start
          # You can add additional deployment steps here, such as copying files to a remote server.

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test

